#!/bin/sh
#Script to launch respective programs and folders
cd ~/OneDrive/Studium/9.\ Semester\ -\ Master/
if [ $# -gt 0 ]
then 
	if [ $1 = "ids" ]
	then 
		cd Introduction\ to\ Data\ Science/
		# if [ $2 = "a" ] 
		# # stands for assignments
		# then
		# 	charm &
		# 	disown
		# 	konsole --workdir  ~/Git/machine-learning &
		# 	disown
		# fi
	fi
	if [ $1 = "se" ]
	then
		cd SE\ Seminar
	fi
	if [ $1 = "or" ]
	then
		cd OR\ Praktikum
	fi
	# if [ $1 = "lopro" ]
	# then
	# 	cd Logikprogrammierung
	# fi
fi
onedrive --synchronize
