#!/bin/sh
#Script to launch respective programs and folders
cd ~/OneDrive/Studium/8.\ Semester\ -\ Master/
if [ $# -gt 0 ]
then 
	if [ $1 = "ml" ]
	then 
		cd Machine\ Learning/
		if [ $2 = "a" ] 
		# stands for assignments
		then
			charm &
			disown
			konsole --workdir  ~/Git/machine-learning &
			disown
		fi
	fi
	if [ $1 = "lopro" ]
	then
		cd Logikprogrammierung
	fi
	if [ $1 = "swa" ]
    then 
        cd Software\ Architectures
    fi
	if  [ $1 = "swp" ]
	then
		cd Software\ Projektmanagement
	fi
fi
onedrive --synchronize
